## Photo Analyzer Test

In [1]:
import pandas as pd
import numpy as np
from deepface import DeepFace
import os

2025-04-29 20:56:08.811119: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [3]:
ceo_data = pd.read_csv('ceo_data.csv')

ceo_data

          Company Ticker  Year            CEO
0      Apple Inc.   AAPL  2010     Steve Jobs
1      Apple Inc.   AAPL  2011       Tim Cook
2      Apple Inc.   AAPL  2012       Tim Cook
3      Apple Inc.   AAPL  2013       Tim Cook
4      Apple Inc.   AAPL  2014       Tim Cook
..            ...    ...   ...            ...
675  VMware, Inc.    VMW  2015  Pat Gelsinger
676  VMware, Inc.    VMW  2016  Pat Gelsinger
677  VMware, Inc.    VMW  2017  Pat Gelsinger
678  VMware, Inc.    VMW  2018  Pat Gelsinger
679  VMware, Inc.    VMW  2019  Pat Gelsinger

[680 rows x 4 columns]

In [4]:

# Analyze the image
result = DeepFace.analyze(img_path="Maya Zucker Headshot.jpg", actions=['age', 'gender', 'race', 'emotion'], detector_backend='opencv')

# If result is a list, get the first item
data = result[0] if isinstance(result, list) else result

# Flatten the nested dictionaries
flat_data = {
    'age': data['age'],
    'dominant_gender': data['dominant_gender'],
    'dominant_race': data['dominant_race'],
    'dominant_emotion': data['dominant_emotion'],
    **data['gender'],
    **data['race'],
    **data['emotion']
}

# Create DataFrame
df = pd.DataFrame([flat_data])


df

Action: emotion: 100%|████████████████████████████| 4/4 [00:07<00:00,  1.78s/it]

,age,dominant_gender,dominant_race,dominant_emotion,Woman,Man,asian,indian,black,white,middle eastern,latino hispanic,angry,disgust,fear,happy,sad,surprise,neutral
0,35,Woman,white,happy,99.240017,0.759981,0.002108,0.508773,0.000252,45.73451,43.953866,9.800492,1.122364e-07,6.046475e-10,0.000002,99.979717,0.000013,0.000002,0.020273

In [ ]:
# Folder containing subfolders with images
base_dir = 

# List to store all analysis results
all_data = []

# Loop through all folders and files
for root, dirs, files in os.walk(base_dir):
    for file in files:
        if file.lower().endswith(('.jpg', '.jpeg', '.png')):
            img_path = os.path.join(root, file)
            try:
                result = DeepFace.analyze(img_path=img_path,
                                          actions=['age', 'gender', 'race', 'emotion'],
                                          detector_backend='opencv')
                data = result[0] if isinstance(result, list) else result

                # Flatten nested results
                flat_data = {
                    'file_path': img_path,
                    'age': data['age'],
                    'dominant_gender': data['dominant_gender'],
                    'dominant_race': data['dominant_race'],
                    'dominant_emotion': data['dominant_emotion'],
                    **data['gender'],
                    **data['race'],
                    **data['emotion']
                }

                all_data.append(flat_data)
            except Exception as e:
                print(f"Error processing {img_path}: {e}")

# Create a DataFrame of all results
df = pd.DataFrame(all_data)

# Save to CSV (optional)
df.to_csv("face_analysis_results.csv", index=False)

# Display the DataFrame
print(df)